name: Test colcon-python-project-example

on:
  schedule:
    - cron: '17 8 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Build example workspace on humble
        id: humble-install
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          build-args: |
            ROS_DISTRO="humble"
            COLCON_BUILD_ARSG=""
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build example workspace on humble with symlink install
        id: humble-symlink-install
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          build-args: |
            ROS_DISTRO="humble"
            COLCON_BUILD_ARSG="--symlink-install"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build example workspace on humble with merge install
        id: humble-merge-install
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          build-args: |
            ROS_DISTRO="humble"
            COLCON_BUILD_ARSG="--merge-install"
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Build example workspace on iron
        id: iron-install
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          build-args: |
            ROS_DISTRO="iron"
            COLCON_BUILD_ARSG=""
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build example workspace on iron with symlink install
        id: iron-symlink-install
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          build-args: |
            ROS_DISTRO="iron"
            COLCON_BUILD_ARSG="--symlink-install"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build example workspace on iron with merge install
        id: iron-merge-install
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          build-args: |
            ROS_DISTRO="humble"
            COLCON_BUILD_ARSG="--merge-install"
          cache-from: type=gha
          cache-to: type=gha,mode=max
